#############################################################################
# Makefile for building: project_zolotykh
# Generated by qmake (2.01a) (Qt 4.8.1) on: Tue Dec 9 23:39:15 2014
# Project:  project_zolotykh.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile project_zolotykh.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Ilib -Iheader -Iqt -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = lib/Netflix.cpp \
		qt/LoggedInWindow.cpp \
		qt/MainMenu.cpp \
		qt/NewUser.cpp \
		qt/RateMovie.cpp \
		qt/RatingsWindow.cpp \
		qt/SearchWindow.cpp \
		src/Movie.cpp \
		src/movies.cpp \
		src/User.cpp moc_LoggedInWindow.cpp \
		moc_MainMenu.cpp \
		moc_NewUser.cpp \
		moc_RateMovie.cpp \
		moc_RatingsWindow.cpp \
		moc_SearchWindow.cpp
OBJECTS       = Netflix.o \
		LoggedInWindow.o \
		MainMenu.o \
		NewUser.o \
		RateMovie.o \
		RatingsWindow.o \
		SearchWindow.o \
		Movie.o \
		movies.o \
		User.o \
		moc_LoggedInWindow.o \
		moc_MainMenu.o \
		moc_NewUser.o \
		moc_RateMovie.o \
		moc_RatingsWindow.o \
		moc_SearchWindow.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		project_zolotykh.pro
QMAKE_TARGET  = project_zolotykh
DESTDIR       = 
TARGET        = project_zolotykh

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: project_zolotykh.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile project_zolotykh.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile project_zolotykh.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/project_zolotykh1.0.0 || $(MKDIR) .tmp/project_zolotykh1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/project_zolotykh1.0.0/ && $(COPY_FILE) --parents header/Movie.h header/User.h lib/map.h lib/Netflix.h lib/queue.h lib/set.h qt/LoggedInWindow.h qt/MainMenu.h qt/NewUser.h qt/RateMovie.h qt/RatingsWindow.h qt/SearchWindow.h .tmp/project_zolotykh1.0.0/ && $(COPY_FILE) --parents lib/Netflix.cpp qt/LoggedInWindow.cpp qt/MainMenu.cpp qt/NewUser.cpp qt/RateMovie.cpp qt/RatingsWindow.cpp qt/SearchWindow.cpp src/Movie.cpp src/movies.cpp src/User.cpp .tmp/project_zolotykh1.0.0/ && (cd `dirname .tmp/project_zolotykh1.0.0` && $(TAR) project_zolotykh1.0.0.tar project_zolotykh1.0.0 && $(COMPRESS) project_zolotykh1.0.0.tar) && $(MOVE) `dirname .tmp/project_zolotykh1.0.0`/project_zolotykh1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/project_zolotykh1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_LoggedInWindow.cpp moc_MainMenu.cpp moc_NewUser.cpp moc_RateMovie.cpp moc_RatingsWindow.cpp moc_SearchWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_LoggedInWindow.cpp moc_MainMenu.cpp moc_NewUser.cpp moc_RateMovie.cpp moc_RatingsWindow.cpp moc_SearchWindow.cpp
moc_LoggedInWindow.cpp: qt/LoggedInWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qt/LoggedInWindow.h -o moc_LoggedInWindow.cpp

moc_MainMenu.cpp: lib/Netflix.h \
		header/User.h \
		header/Movie.h \
		qt/NewUser.h \
		qt/LoggedInWindow.h \
		qt/SearchWindow.h \
		qt/RateMovie.h \
		qt/RatingsWindow.h \
		qt/MainMenu.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qt/MainMenu.h -o moc_MainMenu.cpp

moc_NewUser.cpp: qt/NewUser.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qt/NewUser.h -o moc_NewUser.cpp

moc_RateMovie.cpp: qt/RateMovie.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qt/RateMovie.h -o moc_RateMovie.cpp

moc_RatingsWindow.cpp: lib/Netflix.h \
		header/User.h \
		header/Movie.h \
		qt/RatingsWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qt/RatingsWindow.h -o moc_RatingsWindow.cpp

moc_SearchWindow.cpp: qt/SearchWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qt/SearchWindow.h -o moc_SearchWindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

Netflix.o: lib/Netflix.cpp lib/Netflix.h \
		header/User.h \
		header/Movie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Netflix.o lib/Netflix.cpp

LoggedInWindow.o: qt/LoggedInWindow.cpp qt/LoggedInWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LoggedInWindow.o qt/LoggedInWindow.cpp

MainMenu.o: qt/MainMenu.cpp qt/MainMenu.h \
		lib/Netflix.h \
		header/User.h \
		header/Movie.h \
		qt/NewUser.h \
		qt/LoggedInWindow.h \
		qt/SearchWindow.h \
		qt/RateMovie.h \
		qt/RatingsWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainMenu.o qt/MainMenu.cpp

NewUser.o: qt/NewUser.cpp qt/NewUser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NewUser.o qt/NewUser.cpp

RateMovie.o: qt/RateMovie.cpp qt/RateMovie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RateMovie.o qt/RateMovie.cpp

RatingsWindow.o: qt/RatingsWindow.cpp qt/RatingsWindow.h \
		lib/Netflix.h \
		header/User.h \
		header/Movie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RatingsWindow.o qt/RatingsWindow.cpp

SearchWindow.o: qt/SearchWindow.cpp qt/SearchWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SearchWindow.o qt/SearchWindow.cpp

Movie.o: src/Movie.cpp header/Movie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Movie.o src/Movie.cpp

movies.o: src/movies.cpp qt/MainMenu.h \
		lib/Netflix.h \
		header/User.h \
		header/Movie.h \
		qt/NewUser.h \
		qt/LoggedInWindow.h \
		qt/SearchWindow.h \
		qt/RateMovie.h \
		qt/RatingsWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o movies.o src/movies.cpp

User.o: src/User.cpp header/User.h \
		header/Movie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o User.o src/User.cpp

moc_LoggedInWindow.o: moc_LoggedInWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_LoggedInWindow.o moc_LoggedInWindow.cpp

moc_MainMenu.o: moc_MainMenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainMenu.o moc_MainMenu.cpp

moc_NewUser.o: moc_NewUser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_NewUser.o moc_NewUser.cpp

moc_RateMovie.o: moc_RateMovie.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_RateMovie.o moc_RateMovie.cpp

moc_RatingsWindow.o: moc_RatingsWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_RatingsWindow.o moc_RatingsWindow.cpp

moc_SearchWindow.o: moc_SearchWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SearchWindow.o moc_SearchWindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

